/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Body;
import io.swagger.model.TodoList;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-29T19:37:26.578Z")

@Api(value = "lists", description = "the lists API")
public interface ListsApi {

    @ApiOperation(value = "Add a new TodoList", nickname = "addTodoList", notes = "", tags={ "todo-list", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/lists",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTodoList(@ApiParam(value = "Name for TodoList to be added to the store" ,required=true )  @Valid @RequestBody Body body);


    @ApiOperation(value = "Deletes a TodoList", nickname = "deleteList", notes = "", tags={ "todo-list", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "TodoList not found") })
    @RequestMapping(value = "/lists/{listId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteList(@ApiParam(value = "TodoList id to delete",required=true) @PathVariable("listId") String listId);


    @ApiOperation(value = "Returns all TodoLists", nickname = "getAllTodoLists", notes = "", response = TodoList.class, responseContainer = "List", tags={ "todo-list", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TodoList.class, responseContainer = "List") })
    @RequestMapping(value = "/lists",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<TodoList>> getAllTodoLists();


    @ApiOperation(value = "Returns specified TodoList", nickname = "getTodoList", notes = "", response = TodoList.class, tags={ "todo-list", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TodoList.class) })
    @RequestMapping(value = "/lists/{listId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<TodoList> getTodoList(@ApiParam(value = "TodoList id to get",required=true) @PathVariable("listId") String listId);

}
